spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kamiii?serverTimezone=GMT%2b8&characterEncoding=utf-8
    username: root
    password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

#mybatis:
#  type-aliases-package: com.kamiii.managersystem.entity
#  mapper-locations: classpath:mapping/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.kamiii.managersystem.entity
  global-config:
    db-config:
      table-prefix: sys_
      logic-delete-field: is_delete

